export const metadata = {
  title: "Title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#18181B" />
      </head>
      <body>{children}</body>
    </html>
  );
}
